from enum import Enum
from capstone import x86_const

EFLAGS_GROUP_TEST = (
    x86_const.X86_EFLAGS_TEST_OF | x86_const.X86_EFLAGS_TEST_SF | x86_const.X86_EFLAGS_TEST_ZF |
    x86_const.X86_EFLAGS_TEST_PF | x86_const.X86_EFLAGS_TEST_CF | x86_const.X86_EFLAGS_TEST_DF |
    x86_const.X86_EFLAGS_TEST_AF
)
EFLAGS_GROUP_MODIFY = (
    x86_const.X86_EFLAGS_MODIFY_OF | x86_const.X86_EFLAGS_MODIFY_SF | x86_const.X86_EFLAGS_MODIFY_ZF |
    x86_const.X86_EFLAGS_MODIFY_PF | x86_const.X86_EFLAGS_MODIFY_CF | x86_const.X86_EFLAGS_MODIFY_DF |
    x86_const.X86_EFLAGS_MODIFY_AF
)
EFLAGS_GROUP_SET = (
    x86_const.X86_EFLAGS_SET_CF | x86_const.X86_EFLAGS_SET_DF | x86_const.X86_EFLAGS_SET_OF |
    x86_const.X86_EFLAGS_SET_SF | x86_const.X86_EFLAGS_SET_ZF | x86_const.X86_EFLAGS_SET_AF |
    x86_const.X86_EFLAGS_SET_PF
)
EFLAGS_GROUP_RESET = (
    x86_const.X86_EFLAGS_RESET_OF | x86_const.X86_EFLAGS_RESET_CF | x86_const.X86_EFLAGS_RESET_DF |
    x86_const.X86_EFLAGS_RESET_SF | x86_const.X86_EFLAGS_RESET_AF | x86_const.X86_EFLAGS_RESET_ZF
)
EFLAGS_GROUP_UNDEFINED = (
    x86_const.X86_EFLAGS_UNDEFINED_OF | x86_const.X86_EFLAGS_UNDEFINED_SF | x86_const.X86_EFLAGS_UNDEFINED_ZF |
    x86_const.X86_EFLAGS_UNDEFINED_PF | x86_const.X86_EFLAGS_UNDEFINED_AF | x86_const.X86_EFLAGS_UNDEFINED_CF
)

EFLAGS_MOD_CF = (x86_const.X86_EFLAGS_SET_CF | x86_const.X86_EFLAGS_UNDEFINED_CF | x86_const.X86_EFLAGS_RESET_OF | x86_const.X86_EFLAGS_MODIFY_CF)
EFLAGS_MOD_OF = (x86_const.X86_EFLAGS_SET_OF | x86_const.X86_EFLAGS_UNDEFINED_OF | x86_const.X86_EFLAGS_RESET_OF | x86_const.X86_EFLAGS_MODIFY_OF)
EFLAGS_MOD_ZF = (x86_const.X86_EFLAGS_SET_ZF | x86_const.X86_EFLAGS_UNDEFINED_ZF | x86_const.X86_EFLAGS_RESET_ZF | x86_const.X86_EFLAGS_MODIFY_ZF)
EFLAGS_MOD_DF = (x86_const.X86_EFLAGS_SET_DF | x86_const.X86_EFLAGS_RESET_DF | x86_const.X86_EFLAGS_MODIFY_DF)
EFLAGS_MOD_SF = (x86_const.X86_EFLAGS_SET_SF | x86_const.X86_EFLAGS_UNDEFINED_SF | x86_const.X86_EFLAGS_RESET_SF | x86_const.X86_EFLAGS_MODIFY_SF)
EFLAGS_MOD_PF = (x86_const.X86_EFLAGS_SET_PF | x86_const.X86_EFLAGS_UNDEFINED_PF | x86_const.X86_EFLAGS_RESET_PF | x86_const.X86_EFLAGS_MODIFY_PF)
EFLAGS_MOD_AF = (x86_const.X86_EFLAGS_SET_AF | x86_const.X86_EFLAGS_UNDEFINED_AF | x86_const.X86_EFLAGS_RESET_AF | x86_const.X86_EFLAGS_MODIFY_AF)

FlagRegisterIndex = Enum('FlagRegisterIndex', [
    # byte
    "FLAG_REGISTER_IDX_AL",
    "FLAG_REGISTER_IDX_CL",
    "FLAG_REGISTER_IDX_DL",
    "FLAG_REGISTER_IDX_BL",
    "FLAG_REGISTER_IDX_SPL",
    "FLAG_REGISTER_IDX_BPL",
    "FLAG_REGISTER_IDX_SIL",
    "FLAG_REGISTER_IDX_DIL",
    "FLAG_REGISTER_IDX_R8B",
    "FLAG_REGISTER_IDX_R9B",
    "FLAG_REGISTER_IDX_R10B",
    "FLAG_REGISTER_IDX_R11B",
    "FLAG_REGISTER_IDX_R12B",
    "FLAG_REGISTER_IDX_R13B",
    "FLAG_REGISTER_IDX_R14B",
    "FLAG_REGISTER_IDX_R15B",
    # word
    "FLAG_REGISTER_IDX_AX",
    "FLAG_REGISTER_IDX_CX",
    "FLAG_REGISTER_IDX_DX",
    "FLAG_REGISTER_IDX_BX",
    "FLAG_REGISTER_IDX_SP",
    "FLAG_REGISTER_IDX_BP",
    "FLAG_REGISTER_IDX_SI",
    "FLAG_REGISTER_IDX_DI",
    "FLAG_REGISTER_IDX_R8W",
    "FLAG_REGISTER_IDX_R9W",
    "FLAG_REGISTER_IDX_R10W",
    "FLAG_REGISTER_IDX_R11W",
    "FLAG_REGISTER_IDX_R12W",
    "FLAG_REGISTER_IDX_R13W",
    "FLAG_REGISTER_IDX_R14W",
    "FLAG_REGISTER_IDX_R15W",
    # dword
    "FLAG_REGISTER_IDX_EAX",
    "FLAG_REGISTER_IDX_ECX",
    "FLAG_REGISTER_IDX_EDX",
    "FLAG_REGISTER_IDX_EBX",
    "FLAG_REGISTER_IDX_ESP",
    "FLAG_REGISTER_IDX_EBP",
    "FLAG_REGISTER_IDX_ESI",
    "FLAG_REGISTER_IDX_EDI",
    "FLAG_REGISTER_IDX_R8D",
    "FLAG_REGISTER_IDX_R9D",
    "FLAG_REGISTER_IDX_R10D",
    "FLAG_REGISTER_IDX_R11D",
    "FLAG_REGISTER_IDX_R12D",
    "FLAG_REGISTER_IDX_R13D",
    "FLAG_REGISTER_IDX_R14D",
    "FLAG_REGISTER_IDX_R15D",
    # qword
    "FLAG_REGISTER_IDX_RAX",
    "FLAG_REGISTER_IDX_RCX",
    "FLAG_REGISTER_IDX_RDX",
    "FLAG_REGISTER_IDX_RBX",
    "FLAG_REGISTER_IDX_RSP",
    "FLAG_REGISTER_IDX_RBP",
    "FLAG_REGISTER_IDX_RSI",
    "FLAG_REGISTER_IDX_RDI",
    "FLAG_REGISTER_IDX_R8",
    "FLAG_REGISTER_IDX_R9",
    "FLAG_REGISTER_IDX_R10",
    "FLAG_REGISTER_IDX_R11",
    "FLAG_REGISTER_IDX_R12",
    "FLAG_REGISTER_IDX_R13",
    "FLAG_REGISTER_IDX_R14",
    "FLAG_REGISTER_IDX_R15",
])

# byte
FLAG_REGISTER_AL = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_AL.value
FLAG_REGISTER_CL = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_CL.value
FLAG_REGISTER_DL = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_DL.value
FLAG_REGISTER_BL = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_BL.value
FLAG_REGISTER_SPL = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_SPL.value
FLAG_REGISTER_BPL = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_BPL.value
FLAG_REGISTER_SIL = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_SIL.value
FLAG_REGISTER_DIL = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_DIL.value
FLAG_REGISTER_R8B = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R8B.value
FLAG_REGISTER_R9B = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R9B.value
FLAG_REGISTER_R10B = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R10B.value
FLAG_REGISTER_R11B = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R11B.value
FLAG_REGISTER_R12B = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R12B.value
FLAG_REGISTER_R13B = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R13B.value
FLAG_REGISTER_R14B = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R14B.value
FLAG_REGISTER_R15B = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R15B.value
# word
FLAG_REGISTER_AX = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_AX.value
FLAG_REGISTER_CX = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_CX.value
FLAG_REGISTER_DX = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_DX.value
FLAG_REGISTER_BX = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_BX.value
FLAG_REGISTER_SP = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_SP.value
FLAG_REGISTER_BP = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_BP.value
FLAG_REGISTER_SI = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_SI.value
FLAG_REGISTER_DI = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_DI.value
FLAG_REGISTER_R8W = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R8W.value
FLAG_REGISTER_R9W = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R9W.value
FLAG_REGISTER_R10W = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R10W.value
FLAG_REGISTER_R11W = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R11W.value
FLAG_REGISTER_R12W = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R12W.value
FLAG_REGISTER_R13W = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R13W.value
FLAG_REGISTER_R14W = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R14W.value
FLAG_REGISTER_R15W = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R15W.value
# dword
FLAG_REGISTER_EAX = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_EAX.value
FLAG_REGISTER_ECX = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_ECX.value
FLAG_REGISTER_EDX = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_EDX.value
FLAG_REGISTER_EBX = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_EBX.value
FLAG_REGISTER_ESP = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_ESP.value
FLAG_REGISTER_EBP = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_EBP.value
FLAG_REGISTER_ESI = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_ESI.value
FLAG_REGISTER_EDI = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_EDI.value
FLAG_REGISTER_R8D = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R8D.value
FLAG_REGISTER_R9D = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R9D.value
FLAG_REGISTER_R10D = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R10D.value
FLAG_REGISTER_R11D = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R11D.value
FLAG_REGISTER_R12D = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R12D.value
FLAG_REGISTER_R13D = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R13D.value
FLAG_REGISTER_R14D = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R14D.value
FLAG_REGISTER_R15D = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R15D.value
# qword
FLAG_REGISTER_RAX = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_RAX.value
FLAG_REGISTER_RCX = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_RCX.value
FLAG_REGISTER_RDX = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_RDX.value
FLAG_REGISTER_RBX = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_RBX.value
FLAG_REGISTER_RSP = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_RSP.value
FLAG_REGISTER_RBP = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_RBP.value
FLAG_REGISTER_RSI = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_RSI.value
FLAG_REGISTER_RDI = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_RDI.value
FLAG_REGISTER_R8 = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R8.value
FLAG_REGISTER_R9 = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R9.value
FLAG_REGISTER_R10 = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R10.value
FLAG_REGISTER_R11 = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R11.value
FLAG_REGISTER_R12 = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R12.value
FLAG_REGISTER_R13 = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R13.value
FLAG_REGISTER_R14 = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R14.value
FLAG_REGISTER_R15 = 1 << FlagRegisterIndex.FLAG_REGISTER_IDX_R15.value

REGISTER_ACCESS_READ = 1 << 0
REGISTER_ACCESS_WRITE = 1 << 1

INST_ALLOW_REGISTER = 1 << 0
INST_ALLOW_OPERAND = 1 << 1
INST_ALLOW_IMMEDIATE = 1 << 2

TESTED_FLAGS_TABLE = [
    x86_const.X86_EFLAGS_TEST_OF,
    x86_const.X86_EFLAGS_TEST_SF,
    x86_const.X86_EFLAGS_TEST_ZF,
    x86_const.X86_EFLAGS_TEST_PF,
    x86_const.X86_EFLAGS_TEST_CF,
    x86_const.X86_EFLAGS_TEST_DF,
    x86_const.X86_EFLAGS_TEST_AF
]

EXCLUDED_FLAGS_TABLE = [
    EFLAGS_MOD_OF,
    EFLAGS_MOD_SF,
    EFLAGS_MOD_ZF,
    EFLAGS_MOD_PF,
    EFLAGS_MOD_CF,
    EFLAGS_MOD_DF,
    EFLAGS_MOD_AF
]
